// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for macos - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyD3Hw9Tm5JxwcHv7fdpDvBCZOhN5Py0-UU',
    appId: '1:390944577899:web:bd4376b182d70068f7142e',
    messagingSenderId: '390944577899',
    projectId: 'mymangatheque',
    authDomain: 'mymangatheque.firebaseapp.com',
    storageBucket: 'mymangatheque.appspot.com',
    measurementId: 'G-GGBRFC03CJ',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAq4h5rJN8kUk7vKu5YvkCaISHBQjMiz98',
    appId: '1:390944577899:android:289b432db54b1a9ef7142e',
    messagingSenderId: '390944577899',
    projectId: 'mymangatheque',
    storageBucket: 'mymangatheque.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAAdrTx38SuEocRDswxSryy-_ucgfdRZpU',
    appId: '1:390944577899:ios:69aec6e061eff053f7142e',
    messagingSenderId: '390944577899',
    projectId: 'mymangatheque',
    storageBucket: 'mymangatheque.appspot.com',
    iosBundleId: 'fr.creeperfarm.mymangatheque.myangatheque',
  );
}
